
// This file has been generated by the GUI designer. Do not modify.
namespace MonoDevelop.HaxeBinding.Projects.Gui
{
	public partial class HaxeProjectRunWidget
	{
		private global::Gtk.VBox vbox1;
		private global::Gtk.Frame frame1;
		private global::Gtk.Alignment GtkAlignment;
		private global::Gtk.Table table1;
		private global::Gtk.CheckButton DefaultRunCheck;
		private global::Gtk.Label ExecuteLabel;
		private global::Gtk.HBox hbox1;
		private global::Gtk.Entry OutputEntry;
		private global::Gtk.Button OutputFileButton;
		private global::Gtk.HBox hbox2;
		private global::Gtk.Entry ExecuteEntry;
		private global::Gtk.Button ExecuteFileButton;
		private global::Gtk.Label OutputLabel;
		private global::Gtk.Label GtkLabel2;
		private global::Gtk.Frame frame2;
		private global::Gtk.Alignment GtkAlignment3;
		private global::Gtk.Table table2;
		private global::Gtk.Entry AdditionalArgumentsEntry;
		private global::Gtk.Label AdditionalArgumentsLabel;
		private global::Gtk.Label GtkLabel3;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget MonoDevelop.HaxeBinding.Projects.Gui.HaxeProjectRunWidget
			global::Stetic.BinContainer.Attach (this);
			this.Name = "MonoDevelop.HaxeBinding.Projects.Gui.HaxeProjectRunWidget";
			// Container child MonoDevelop.HaxeBinding.Projects.Gui.HaxeProjectRunWidget.Gtk.Container+ContainerChild
			this.vbox1 = new global::Gtk.VBox ();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			// Container child vbox1.Gtk.Box+BoxChild
			this.frame1 = new global::Gtk.Frame ();
			this.frame1.Name = "frame1";
			this.frame1.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child frame1.Gtk.Container+ContainerChild
			this.GtkAlignment = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.GtkAlignment.Name = "GtkAlignment";
			this.GtkAlignment.LeftPadding = ((uint)(12));
			this.GtkAlignment.TopPadding = ((uint)(12));
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			this.table1 = new global::Gtk.Table (((uint)(4)), ((uint)(2)), false);
			this.table1.Name = "table1";
			this.table1.RowSpacing = ((uint)(6));
			this.table1.ColumnSpacing = ((uint)(12));
			// Container child table1.Gtk.Table+TableChild
			this.DefaultRunCheck = new global::Gtk.CheckButton ();
			this.DefaultRunCheck.CanFocus = true;
			this.DefaultRunCheck.Name = "DefaultRunCheck";
			this.DefaultRunCheck.Label = global::Mono.Unix.Catalog.GetString ("default run");
			this.DefaultRunCheck.DrawIndicator = true;
			this.DefaultRunCheck.UseUnderline = true;
			this.table1.Add (this.DefaultRunCheck);
			global::Gtk.Table.TableChild w1 = ((global::Gtk.Table.TableChild)(this.table1 [this.DefaultRunCheck]));
			w1.LeftAttach = ((uint)(1));
			w1.RightAttach = ((uint)(2));
			w1.XOptions = ((global::Gtk.AttachOptions)(4));
			w1.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.ExecuteLabel = new global::Gtk.Label ();
			this.ExecuteLabel.Name = "ExecuteLabel";
			this.ExecuteLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("Custom program");
			this.table1.Add (this.ExecuteLabel);
			global::Gtk.Table.TableChild w2 = ((global::Gtk.Table.TableChild)(this.table1 [this.ExecuteLabel]));
			w2.TopAttach = ((uint)(2));
			w2.BottomAttach = ((uint)(3));
			w2.XOptions = ((global::Gtk.AttachOptions)(4));
			w2.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.hbox1 = new global::Gtk.HBox ();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.OutputEntry = new global::Gtk.Entry ();
			this.OutputEntry.CanFocus = true;
			this.OutputEntry.Name = "OutputEntry";
			this.OutputEntry.IsEditable = false;
			this.OutputEntry.InvisibleChar = '•';
			this.hbox1.Add (this.OutputEntry);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.OutputEntry]));
			w3.Position = 0;
			// Container child hbox1.Gtk.Box+BoxChild
			this.OutputFileButton = new global::Gtk.Button ();
			this.OutputFileButton.CanFocus = true;
			this.OutputFileButton.Name = "OutputFileButton";
			// Container child OutputFileButton.Gtk.Container+ContainerChild
			global::Gtk.Alignment w4 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w5 = new global::Gtk.HBox ();
			w5.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w6 = new global::Gtk.Image ();
			w6.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-file", global::Gtk.IconSize.Menu);
			w5.Add (w6);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w8 = new global::Gtk.Label ();
			w8.LabelProp = global::Mono.Unix.Catalog.GetString ("Browse...");
			w5.Add (w8);
			w4.Add (w5);
			this.OutputFileButton.Add (w4);
			this.hbox1.Add (this.OutputFileButton);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.OutputFileButton]));
			w12.Position = 1;
			w12.Expand = false;
			w12.Fill = false;
			this.table1.Add (this.hbox1);
			global::Gtk.Table.TableChild w13 = ((global::Gtk.Table.TableChild)(this.table1 [this.hbox1]));
			w13.TopAttach = ((uint)(1));
			w13.BottomAttach = ((uint)(2));
			w13.LeftAttach = ((uint)(1));
			w13.RightAttach = ((uint)(2));
			w13.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.hbox2 = new global::Gtk.HBox ();
			this.hbox2.Name = "hbox2";
			this.hbox2.Spacing = 6;
			// Container child hbox2.Gtk.Box+BoxChild
			this.ExecuteEntry = new global::Gtk.Entry ();
			this.ExecuteEntry.CanFocus = true;
			this.ExecuteEntry.Name = "ExecuteEntry";
			this.ExecuteEntry.IsEditable = false;
			this.ExecuteEntry.InvisibleChar = '●';
			this.hbox2.Add (this.ExecuteEntry);
			global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.ExecuteEntry]));
			w14.Position = 0;
			// Container child hbox2.Gtk.Box+BoxChild
			this.ExecuteFileButton = new global::Gtk.Button ();
			this.ExecuteFileButton.CanFocus = true;
			this.ExecuteFileButton.Name = "ExecuteFileButton";
			this.ExecuteFileButton.UseUnderline = true;
			// Container child ExecuteFileButton.Gtk.Container+ContainerChild
			global::Gtk.Alignment w15 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w16 = new global::Gtk.HBox ();
			w16.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w17 = new global::Gtk.Image ();
			w17.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-execute", global::Gtk.IconSize.Menu);
			w16.Add (w17);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w19 = new global::Gtk.Label ();
			w19.LabelProp = global::Mono.Unix.Catalog.GetString ("Browse...");
			w19.UseUnderline = true;
			w16.Add (w19);
			w15.Add (w16);
			this.ExecuteFileButton.Add (w15);
			this.hbox2.Add (this.ExecuteFileButton);
			global::Gtk.Box.BoxChild w23 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.ExecuteFileButton]));
			w23.Position = 1;
			w23.Expand = false;
			w23.Fill = false;
			this.table1.Add (this.hbox2);
			global::Gtk.Table.TableChild w24 = ((global::Gtk.Table.TableChild)(this.table1 [this.hbox2]));
			w24.TopAttach = ((uint)(2));
			w24.BottomAttach = ((uint)(3));
			w24.LeftAttach = ((uint)(1));
			w24.RightAttach = ((uint)(2));
			w24.XOptions = ((global::Gtk.AttachOptions)(4));
			w24.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.OutputLabel = new global::Gtk.Label ();
			this.OutputLabel.Name = "OutputLabel";
			this.OutputLabel.Xalign = 0F;
			this.OutputLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("File or URL");
			this.table1.Add (this.OutputLabel);
			global::Gtk.Table.TableChild w25 = ((global::Gtk.Table.TableChild)(this.table1 [this.OutputLabel]));
			w25.TopAttach = ((uint)(1));
			w25.BottomAttach = ((uint)(2));
			w25.XOptions = ((global::Gtk.AttachOptions)(4));
			w25.YOptions = ((global::Gtk.AttachOptions)(4));
			this.GtkAlignment.Add (this.table1);
			this.frame1.Add (this.GtkAlignment);
			this.GtkLabel2 = new global::Gtk.Label ();
			this.GtkLabel2.Name = "GtkLabel2";
			this.GtkLabel2.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Run</b>");
			this.GtkLabel2.UseMarkup = true;
			this.frame1.LabelWidget = this.GtkLabel2;
			this.vbox1.Add (this.frame1);
			global::Gtk.Box.BoxChild w28 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.frame1]));
			w28.Position = 0;
			// Container child vbox1.Gtk.Box+BoxChild
			this.frame2 = new global::Gtk.Frame ();
			this.frame2.Name = "frame2";
			this.frame2.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child frame2.Gtk.Container+ContainerChild
			this.GtkAlignment3 = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.GtkAlignment3.Name = "GtkAlignment3";
			this.GtkAlignment3.LeftPadding = ((uint)(12));
			this.GtkAlignment3.TopPadding = ((uint)(12));
			// Container child GtkAlignment3.Gtk.Container+ContainerChild
			this.table2 = new global::Gtk.Table (((uint)(1)), ((uint)(2)), false);
			this.table2.Name = "table2";
			this.table2.RowSpacing = ((uint)(6));
			this.table2.ColumnSpacing = ((uint)(6));
			// Container child table2.Gtk.Table+TableChild
			this.AdditionalArgumentsEntry = new global::Gtk.Entry ();
			this.AdditionalArgumentsEntry.CanFocus = true;
			this.AdditionalArgumentsEntry.Name = "AdditionalArgumentsEntry";
			this.AdditionalArgumentsEntry.IsEditable = true;
			this.AdditionalArgumentsEntry.InvisibleChar = '•';
			this.table2.Add (this.AdditionalArgumentsEntry);
			global::Gtk.Table.TableChild w29 = ((global::Gtk.Table.TableChild)(this.table2 [this.AdditionalArgumentsEntry]));
			w29.LeftAttach = ((uint)(1));
			w29.RightAttach = ((uint)(2));
			w29.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.AdditionalArgumentsLabel = new global::Gtk.Label ();
			this.AdditionalArgumentsLabel.Name = "AdditionalArgumentsLabel";
			this.AdditionalArgumentsLabel.Xalign = 0F;
			this.AdditionalArgumentsLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("Additional arguments:");
			this.table2.Add (this.AdditionalArgumentsLabel);
			global::Gtk.Table.TableChild w30 = ((global::Gtk.Table.TableChild)(this.table2 [this.AdditionalArgumentsLabel]));
			w30.XOptions = ((global::Gtk.AttachOptions)(4));
			w30.YOptions = ((global::Gtk.AttachOptions)(4));
			this.GtkAlignment3.Add (this.table2);
			this.frame2.Add (this.GtkAlignment3);
			this.GtkLabel3 = new global::Gtk.Label ();
			this.GtkLabel3.Name = "GtkLabel3";
			this.GtkLabel3.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Options</b>");
			this.GtkLabel3.UseMarkup = true;
			this.frame2.LabelWidget = this.GtkLabel3;
			this.vbox1.Add (this.frame2);
			global::Gtk.Box.BoxChild w33 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.frame2]));
			w33.Position = 1;
			w33.Expand = false;
			w33.Fill = false;
			this.Add (this.vbox1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
			this.ExecuteFileButton.Clicked += new global::System.EventHandler (this.onCustomProgramSelect);
			this.OutputFileButton.Clicked += new global::System.EventHandler (this.OnOutputButtonClicked);
			this.DefaultRunCheck.Toggled += new global::System.EventHandler (this.onDefaultBuildCheck);
		}
	}
}
