
// This file has been generated by the GUI designer. Do not modify.
namespace MonoDevelop.HaxeBinding.Projects.Gui
{
	public partial class HaxeProjectRunWidget
	{
		private global::Gtk.VBox vbox1;
		private global::Gtk.Frame frame1;
		private global::Gtk.Alignment GtkAlignment;
		private global::Gtk.Table table1;
		private global::Gtk.Label ExecuteLabel;
		private global::Gtk.HBox hbox1;
		private global::Gtk.Entry OutputEntry;
		private global::Gtk.Button OutputFileButton;
		private global::Gtk.HBox hbox2;
		private global::Gtk.Entry ExecuteEntry;
		private global::Gtk.Button ExecuteFileButton;
		private global::Gtk.Label OutputLabel;
		private global::Gtk.Label GtkLabel1;
		private global::Gtk.Frame frame2;
		private global::Gtk.Alignment GtkAlignment2;
		private global::Gtk.Table table2;
		private global::Gtk.Entry AdditionalArgumentsEntry;
		private global::Gtk.Label AdditionalArgumentsLabel;
		private global::Gtk.Label GtkLabel2;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget MonoDevelop.HaxeBinding.Projects.Gui.HaxeProjectRunWidget
			global::Stetic.BinContainer.Attach (this);
			this.Name = "MonoDevelop.HaxeBinding.Projects.Gui.HaxeProjectRunWidget";
			// Container child MonoDevelop.HaxeBinding.Projects.Gui.HaxeProjectRunWidget.Gtk.Container+ContainerChild
			this.vbox1 = new global::Gtk.VBox ();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			// Container child vbox1.Gtk.Box+BoxChild
			this.frame1 = new global::Gtk.Frame ();
			this.frame1.Name = "frame1";
			this.frame1.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child frame1.Gtk.Container+ContainerChild
			this.GtkAlignment = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.GtkAlignment.Name = "GtkAlignment";
			this.GtkAlignment.LeftPadding = ((uint)(12));
			this.GtkAlignment.TopPadding = ((uint)(12));
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			this.table1 = new global::Gtk.Table (((uint)(3)), ((uint)(2)), false);
			this.table1.Name = "table1";
			this.table1.RowSpacing = ((uint)(6));
			this.table1.ColumnSpacing = ((uint)(12));
			// Container child table1.Gtk.Table+TableChild
			this.ExecuteLabel = new global::Gtk.Label ();
			this.ExecuteLabel.Name = "ExecuteLabel";
			this.ExecuteLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("Custom program");
			this.table1.Add (this.ExecuteLabel);
			global::Gtk.Table.TableChild w1 = ((global::Gtk.Table.TableChild)(this.table1 [this.ExecuteLabel]));
			w1.TopAttach = ((uint)(1));
			w1.BottomAttach = ((uint)(2));
			w1.XOptions = ((global::Gtk.AttachOptions)(4));
			w1.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.hbox1 = new global::Gtk.HBox ();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.OutputEntry = new global::Gtk.Entry ();
			this.OutputEntry.CanFocus = true;
			this.OutputEntry.Name = "OutputEntry";
			this.OutputEntry.IsEditable = true;
			this.OutputEntry.InvisibleChar = '•';
			this.hbox1.Add (this.OutputEntry);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.OutputEntry]));
			w2.Position = 0;
			// Container child hbox1.Gtk.Box+BoxChild
			this.OutputFileButton = new global::Gtk.Button ();
			this.OutputFileButton.CanFocus = true;
			this.OutputFileButton.Name = "OutputFileButton";
			this.OutputFileButton.Label = global::Mono.Unix.Catalog.GetString ("Browse...");
			global::Gtk.Image w3 = new global::Gtk.Image ();
			w3.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-file", global::Gtk.IconSize.Menu);
			this.OutputFileButton.Image = w3;
			this.hbox1.Add (this.OutputFileButton);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.OutputFileButton]));
			w4.Position = 1;
			w4.Expand = false;
			w4.Fill = false;
			this.table1.Add (this.hbox1);
			global::Gtk.Table.TableChild w5 = ((global::Gtk.Table.TableChild)(this.table1 [this.hbox1]));
			w5.LeftAttach = ((uint)(1));
			w5.RightAttach = ((uint)(2));
			w5.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.hbox2 = new global::Gtk.HBox ();
			this.hbox2.Name = "hbox2";
			this.hbox2.Spacing = 6;
			// Container child hbox2.Gtk.Box+BoxChild
			this.ExecuteEntry = new global::Gtk.Entry ();
			this.ExecuteEntry.CanFocus = true;
			this.ExecuteEntry.Name = "ExecuteEntry";
			this.ExecuteEntry.IsEditable = true;
			this.ExecuteEntry.InvisibleChar = '●';
			this.hbox2.Add (this.ExecuteEntry);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.ExecuteEntry]));
			w6.Position = 0;
			// Container child hbox2.Gtk.Box+BoxChild
			this.ExecuteFileButton = new global::Gtk.Button ();
			this.ExecuteFileButton.CanFocus = true;
			this.ExecuteFileButton.Name = "ExecuteFileButton";
			this.ExecuteFileButton.UseUnderline = true;
			this.ExecuteFileButton.Label = global::Mono.Unix.Catalog.GetString ("Browse...");
			global::Gtk.Image w7 = new global::Gtk.Image ();
			w7.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-execute", global::Gtk.IconSize.Menu);
			this.ExecuteFileButton.Image = w7;
			this.hbox2.Add (this.ExecuteFileButton);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.ExecuteFileButton]));
			w8.Position = 1;
			w8.Expand = false;
			w8.Fill = false;
			this.table1.Add (this.hbox2);
			global::Gtk.Table.TableChild w9 = ((global::Gtk.Table.TableChild)(this.table1 [this.hbox2]));
			w9.TopAttach = ((uint)(1));
			w9.BottomAttach = ((uint)(2));
			w9.LeftAttach = ((uint)(1));
			w9.RightAttach = ((uint)(2));
			w9.XOptions = ((global::Gtk.AttachOptions)(4));
			w9.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.OutputLabel = new global::Gtk.Label ();
			this.OutputLabel.Name = "OutputLabel";
			this.OutputLabel.Xalign = 0F;
			this.OutputLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("File or URL");
			this.table1.Add (this.OutputLabel);
			global::Gtk.Table.TableChild w10 = ((global::Gtk.Table.TableChild)(this.table1 [this.OutputLabel]));
			w10.XOptions = ((global::Gtk.AttachOptions)(4));
			w10.YOptions = ((global::Gtk.AttachOptions)(4));
			this.GtkAlignment.Add (this.table1);
			this.frame1.Add (this.GtkAlignment);
			this.GtkLabel1 = new global::Gtk.Label ();
			this.GtkLabel1.Name = "GtkLabel1";
			this.GtkLabel1.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Run</b>");
			this.GtkLabel1.UseMarkup = true;
			this.frame1.LabelWidget = this.GtkLabel1;
			this.vbox1.Add (this.frame1);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.frame1]));
			w13.Position = 0;
			// Container child vbox1.Gtk.Box+BoxChild
			this.frame2 = new global::Gtk.Frame ();
			this.frame2.Name = "frame2";
			this.frame2.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child frame2.Gtk.Container+ContainerChild
			this.GtkAlignment2 = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.GtkAlignment2.Name = "GtkAlignment2";
			this.GtkAlignment2.LeftPadding = ((uint)(12));
			this.GtkAlignment2.TopPadding = ((uint)(12));
			// Container child GtkAlignment2.Gtk.Container+ContainerChild
			this.table2 = new global::Gtk.Table (((uint)(1)), ((uint)(2)), false);
			this.table2.Name = "table2";
			this.table2.RowSpacing = ((uint)(6));
			this.table2.ColumnSpacing = ((uint)(6));
			// Container child table2.Gtk.Table+TableChild
			this.AdditionalArgumentsEntry = new global::Gtk.Entry ();
			this.AdditionalArgumentsEntry.CanFocus = true;
			this.AdditionalArgumentsEntry.Name = "AdditionalArgumentsEntry";
			this.AdditionalArgumentsEntry.IsEditable = true;
			this.AdditionalArgumentsEntry.InvisibleChar = '•';
			this.table2.Add (this.AdditionalArgumentsEntry);
			global::Gtk.Table.TableChild w14 = ((global::Gtk.Table.TableChild)(this.table2 [this.AdditionalArgumentsEntry]));
			w14.LeftAttach = ((uint)(1));
			w14.RightAttach = ((uint)(2));
			w14.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.AdditionalArgumentsLabel = new global::Gtk.Label ();
			this.AdditionalArgumentsLabel.Name = "AdditionalArgumentsLabel";
			this.AdditionalArgumentsLabel.Xalign = 0F;
			this.AdditionalArgumentsLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("Additional arguments:");
			this.table2.Add (this.AdditionalArgumentsLabel);
			global::Gtk.Table.TableChild w15 = ((global::Gtk.Table.TableChild)(this.table2 [this.AdditionalArgumentsLabel]));
			w15.XOptions = ((global::Gtk.AttachOptions)(4));
			w15.YOptions = ((global::Gtk.AttachOptions)(4));
			this.GtkAlignment2.Add (this.table2);
			this.frame2.Add (this.GtkAlignment2);
			this.GtkLabel2 = new global::Gtk.Label ();
			this.GtkLabel2.Name = "GtkLabel2";
			this.GtkLabel2.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Options</b>");
			this.GtkLabel2.UseMarkup = true;
			this.frame2.LabelWidget = this.GtkLabel2;
			this.vbox1.Add (this.frame2);
			global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.frame2]));
			w18.Position = 1;
			w18.Expand = false;
			w18.Fill = false;
			this.Add (this.vbox1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
			this.OutputFileButton.Clicked += new global::System.EventHandler (this.OnOutputButtonClicked);
		}
	}
}
